openapi: 3.0.1
info:
  title: PDU - OOTS API defintion
  version: v0.1
servers:
  - url: 'http://localhost:8080'
    description: Generated server url
paths:

  '/eb/procedureTypes':
    get:
      tags:
        - evidence-broker-controller
      summary: Search for a list of procedure types
      description: Returns a list of procedures types supported by SDG OOTS.
      operationId: lookupProcedureTypes
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProcedureType'
  /eb/procedures:
    post:
      tags:
        - evidence-broker-controller
      summary: >-
        Create procedure and send it to evidence broker
      description: >-
        Create a new procedure in Evidence Broker through ebXML to common services.
      operationId: createProcedureEb
      requestBody:
        required: true
        content:
          application/json:
            schema:
             $ref: '#/components/schemas/Procedure'
      responses:
        '201':
          description: Created
  /eb/procedures/{procedureId}:
    put:
      tags:
        - evidence-broker-controller
      summary: >-
        Update a procedure and send it to evidence broker
      description: >-
       Update procedure in Evidence Broker through ebXML to common services.
      operationId: updateProcedureEb
      parameters:
        - name: procedureId
          in: path
          required: true
          schema:
            type: string
          example: https://sr.oots.tech.ec.europa.eu/requirements/f8a6a284-34e9-42c7-9733-63b5c4f4aa42
      requestBody:
        required: true
        content:
          application/json:
            schema:
             $ref: '#/components/schemas/Procedure'
      responses:
        '200':
          description: Updated
    get:
      tags:
        - evidence-broker-controller
      summary: Find a list of evidence types
      description: >-
        Returns a list of evidence types classifications for a specific country and a requirement identifier.
      operationId: getProcedureById
      parameters:
        - name: procedureId
          in: path
          required: true
          schema:
            type: string
          example: https://sr.oots.tech.ec.europa.eu/requirements/f8a6a284-34e9-42c7-9733-63b5c4f4aa42
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                  $ref: '#/components/schemas/Procedure'
    delete:
        tags:
          - evidence-broker-controller
        summary: >-
          Delete a procedure and send it to evidence broker
        description: >-
         Delete procedure in Evidence Broker through ebXML to common services.
        operationId: deleteProcedureEb
        parameters:
        - name: procedureId
          in: path
          required: true
          schema:
            type: string
          example: https://sr.oots.tech.ec.europa.eu/requirements/f8a6a284-34e9-42c7-9733-63b5c4f4aa42
        responses:
          '200':
            description: Updated
  '/eb/evidenceTypeClassifications':
    get:
      tags:
        - evidence-broker-controller
      summary: Find a list of evidence types
      description: >-
        Returns a list of evidence types classifications for a specific country and a requirement identifier.
      operationId: lookupEvidenceTypes
      parameters:
        - name: countryCode
          in: query
          required: true
          schema:
            type: string
          example: DE
        - name: requirementId
          in: query
          required: true
          schema:
            type: string
          example: https://sr.oots.tech.ec.europa.eu/requirements/f8a6a284-34e9-42c7-9733-63b5c4f4aa42
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EvidenceTypeClassification'
  /eb/countryCodes:
    get:
      tags:
        - evidence-broker-controller
      summary: Search list of countries
      description: Returns a list of countries suported by SDG.
      operationId: lookupCountryCodes
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CountryCode'
  '/dsd/providers':
    get:
      tags:
        - data-service-directory-controller
      summary: Search for evidence providers
      description: >-
        Find Data Services of Evidence Providers for a specific Evidence Type Classification.
        This query allows the Evidence Requester to find all the Data Services of the Evidence Providers that can provide the required type of Evidence Type and are based in a specific geographic area. It can happen that one provider has more Data Services.
        <br> Return the associations between data services and providers for the providers of evidence type classification provided.
      operationId: lookupEvidenceProviders
      parameters:
        - name: countryCode
          in: query
          required: true
          schema:
            type: string
          example: DE
        - name: evidenceTypeClassificationId
          in: query
          required: true
          schema:
            type: string
          example: https://sr.oots.tech.ec.europa.eu/evidencetypeclassifications/AT/b6a49e54-8b3c-4688-acad-380440dc5962
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EvidenceProvider'
    post:
      tags:
        - data-service-directory-controller
      summary: >-
        Create and send the evidence provider to the Data Service Directory
      description: Create new evidence provider in Data Service Directory
      operationId: createDataServiceEvidenceProvider
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PublisherDataServiceEvidenceProvider'
      responses:
        '201':
          description: Created
  '/dsd/providers/{providersId}':
    put:
      tags:
        - data-service-directory-controller
      summary: >-
        Update and send the evidence provider to the Data Service Directory
      description: Update an existing evidence provider in Data Service Directory
      operationId: putDataServiceEvidenceProvider
      parameters:
        - name: providersId
          in: path
          required: true
          schema:
            type: string
          example: RO4433775
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PublisherDataServiceEvidenceProvider'
      responses:
        '201':
          description: Created
    get:
      tags:
        - data-service-directory-controller
      summary: Get an existing evidence provider
      description: Get an existing evidence provider
      operationId: getEvidenceProvider
      parameters:
        - name: providersId
          in: path
          required: true
          schema:
            type: string
          example: RO4433775
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PublisherDataServiceEvidenceProvider'
    delete:
      tags:
        - data-service-directory-controller
      summary: Search for evidence providers
      parameters:
        - name: providersId
          in: path
          required: true
          schema:
            type: string
          example: RO4433775
      description: Removes the evidence provider from OOTS
      responses:
        '200':
          description: OK
  /dsd/evidenceTypeClassifications:
    post:
      tags:
        - data-service-directory-controller
      summary: >-
        Create and send the evidence type to the Data Service Directory and submit it for review.
      description: Send the evidence type to the Data Service Directory through ebXML to DSD(common services) and Evidence Broker. When arriving in Common Services it will be automatically created as draft. After the draft is created, this endpoint will automatically also submit it for review.
      operationId: createDataServiceEvidenceType
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EvidenceType'
      responses:
        '201':
          description: Created

  /dsd/evidenceTypeClassifications/{evidenceTypeClassificationId}:
    put:
      tags:
        - data-service-directory-controller
      summary: >-
        Edit an existing the evidence type from the Data Service Directory and submit it for review.
      description: Edit the evidence type from the Data Service Directory through ebXML to DSD(common services) and Evidence Broker. First message to DSD will move the evidence type to draft.  After the draft is created the evidence type will be modified, and then this endpoint will automatically also submit it for review.
      parameters:
        - name: evidenceTypeClassificationId
          in: path
          required: true
          schema:
            type: string
          example: https://sr.oots.tech.ec.europa.eu/evidencetypeclassifications/AT/b6a49e54-8b3c-4688-acad-380440dc5962
      operationId: updateDataServiceEvidenceType
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EvidenceType'
      responses:
        '200':
          description: Ok 
    get:
      tags:
        - data-service-directory-controller
      summary: >-
        Get evidence type classification by id
      description: Delete the evidence type from the Data Service Directory through ebXML to DSD(common services) and Evidence Broker. First message to DSD will move the evidence type to draft. After the seccond message will delete the evidence type.
      parameters:
        - name: evidenceTypeClassificationId
          in: path
          required: true
          schema:
            type: string
          example: https://sr.oots.tech.ec.europa.eu/evidencetypeclassifications/AT/b6a49e54-8b3c-4688-acad-380440dc5962
      operationId: getDataServiceEvidenceProviderById
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EvidenceType'
    delete:
      tags:
        - data-service-directory-controller
      summary: >-
        Delete evidence type classification by id.
      description: Delete the evidence type from the Data Service Directory through ebXML to DSD(common services) and Evidence Broker. First message to DSD will move the evidence type to draft. After the seccond message will delete the evidence type.
      parameters:
        - name: evidenceTypeClassificationId
          in: path
          required: true
          schema:
            type: string
          example: https://sr.oots.tech.ec.europa.eu/evidencetypeclassifications/AT/b6a49e54-8b3c-4688-acad-380440dc5962
      operationId: deleteDataServiceEvidenceType
      responses:
        '204':
          description: No content  
          
  '/messaging/evidenceRequests':
    post:
      tags:
        - evidence-exchange-controller
      summary: Start Evidence Request
      description: >-
        User gives the consent to start the evidence request flow and getting
        the link to preview space. Also the second evidence loop starts here.
        In the first loop it returns converationId and previewURL if necessary.
      operationId: startupEvidenceRequest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EvidenceRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  previewURL:
                    type: string
                    example: https://preview.space.example.com/requests/d36af8bc-fea6-4ee5-a32d-5bef82cdb071
                  conversationId:
                    type: string
                    example: 1000f6bf-1403-11ee-8d29-0242ac120002@domibus.eu
  '/messaging/evidenceResponses/{conversationId}':
    get:
      tags:
        - evidence-exchange-controller
      summary: Check the evidence response
      description: >-
        Returns the evidence response after the evidence exchange has
        been completed.
      operationId: listenEvidenceResponse
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
          example: 1000f6bf-1403-11ee-8d29-0242ac120002@domibus.eu
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EvidenceResponse'
  '/preview/evidenceDocuments/{conversationId}':
    get:
      tags:
        - preview-space-controller
      summary: Get the list of available documents to be previewed
      description: >-
        Returns a list of all requested documents(including the type,
        procedure that is part of) and their preview link to the binary
        document.
      operationId: getEvidenceList
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
          example: 1000f6bf-1403-11ee-8d29-0242ac120002@domibus.eu
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PreviewResponse'

  /preview/evidenceConsents:
    post:
      tags:
        - preview-space-controller
      summary: >-
        Give consent to send the evicence documents as response data to MS
        DataService
      description: User gives the consent to start the evidence response flow
      operationId: consentEvidenceRequest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                evidenceDocumentList:
                  items:
                    type: object
                    properties:
                      id:
                        $ref: '#/components/schemas/EvidenceDocument/properties/id'
                      consent:
                        type: boolean
                        example: true
      responses:
        '302':
          description: Redirect to Online Procedural Portal
components:
  schemas:
    Requirement:
      type: object
      required:
          - id
          - nameLang
      properties:
        id:
          type: string
          description: Request identifier
          example: >-
            https://sr.oots.tech.ec.europa.eu/requirements/f8a6a284-34e9-42c7-9733-63b5c4f4aa42
        nameLang:
          type: array
          items:
            type: object
            description: Description of the request
            properties:
              lang:
                type: string
                example: EN
              name:
                type: string
                example: Proof of Birth
      description: >-
        This Registry Object provides the information of a Requirement in any of its derivative forms (Criterion, Information Requirement). It MUST NOT contain any Evidence Type or Reference Frameworks (Procedures) as this are provided dynamically by the use of associations. The classification node used MUST be Requirement under the EB Classification Scheme urn:fdc:oots:classification:eb
    ProcedureType:
      type: object
      properties:
        id:
          type: string
          description: Procedure type identifier
          example: T1
        description:
          type: string
          description: Description of the procedure type
          example: >-
            Applying for a tertiary education study financing, such as study
            grants and loans from a public body or institution
      description: Procedure type
    EvidenceTypeClassification:
      type: object
      properties:
        id:
          type: string
          description: Evidence type identifier
          example: >-
            https://sr.oots.tech.ec.europa.eu/evidencetypeclassifications/EU/b6a49e54-8b3c-4688-acad-380440dc5962
        description:
          type: string
          description: Description of the type of evidence
          example: EU-Wide Diploma/Bachelor's Degree
      description: Tipul probei
    CountryCode:
      type: object
      properties:
        code:
          type: string
          description: In short
          example: RO
        name:
          type: string
          description: Name of the country
          example: Romania
      description: Country abbreviation and name
    EvidenceProvider:
      type: object
      properties:
        id:
          type: string
          description: Provider identifier
          example: DE73524311
        nameLang:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                description: Description of the provider
                example: Civil Registration Office Berlin I
              lang:
                type: string
                example: EN
        evidenceTypeId:
            type: string
            description: Referenced in OOTS documentation and messaging as DataServiceEvidenceType. It represents the association between an Evidence Type and an Evidence Provider. 
            example: d92f7ed9-1ca6-4c55-9389-33ab3263840d
      description: Provider of proof
    EvidenceRequester:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the agent
          example: NL222332239
        Name:
          type: string
          description: Name of the agent
          example: University of Amsterdam
        Address:
          type: object
          properties:
            FullAddress:
              type: string
              description: Full address of the agent
              example: Binnengasthuisstraat 9
            LocatorDesignator:
              type: string
              description: Designator of the locator
              example: 9
            PostCode:
              type: string
              description: Postal code of the agent's address
              example: 1012
            PostCityName:
              type: string
              description: City name of the agent's address
              example: Amsterdam
            AdminUnitLevel1:
              type: string
              description: First administrative unit level of the agent's address
              example: NL
            AdminUnitLevel2:
              type: string
              description: Second administrative unit level of the agent's address
              example: NL329
        Classification:
          type: string
          description: Classification of the agent
          example: ER
    EvidenceRequest:
      type: object
      properties:
        pduServiceId: 
          type: string
          example: a7f30fbb-2585-4101-87be-c1415e3e16f5
        requirementId:
            $ref: '#/components/schemas/Requirement/properties/id'
        evindeceTypeId:
          type: string
          example: 3a24b689-e2f2-41b2-b413-f1e341bd6eec
        evidenceProvider:
            $ref: '#/components/schemas/EvidenceProvider/properties/id'
        possibilityForPreview:
          type: boolean
        conversationId:
          type: string
          description: Only for the second loop request
          example: 1000f6bf-1403-11ee-8d29-0242ac120002@domibus.eu

    EvidenceDocument:
      type: object
      properties:
        id:
          type: string
          example: 123
        evidenceType:
          $ref: '#/components/schemas/EvidenceType'
        AuthenticationLevelOfAssurance:
          type: string
          example: Code
        Note:
          type: string
          example: Text
        NoteTextLang:
          type: string
          example: Code
        DistributedAs:
          type: array
          items:
            $ref: '#/components/schemas/DistributedAs'
        EvidenceProviderJurisdictionDetermination:
          $ref: '#/components/schemas/EvidenceProviderJurisdictionDetermination'
        EvidenceProviderClassification:
          $ref: '#/components/schemas/EvidenceProviderClassification'
        EvidenceProvider:
          type: array
          items:
            $ref: '#/components/schemas/PublisherDataServiceEvidenceProvider/properties/identifier'
        title:
          type: string
          example: Certificate of Birth
        issuingAuthority:
          type: object
          properties:
            identifier:
              type: string
              example: DE73524311
            name:
              type: string
              example: Civil Registration Office Berlin I
        registryUrl:
          type: string
          example: >-
            https://tech.ec.europa.eu/distributions/birthcert-1.0.0/age-of-majority
    EvidenceResponse:
      type: object
      properties:
        evidenceDocumentsList:
          type: array
          items:
            $ref: '#/components/schemas/EvidenceDocument'
    EvidenceType:
      type: object
      required:
        - evidenceTypeClass
        - title
        - titleLang
      properties:
        titleLang:
          type: array
          items:
            type: object
            properties:
              lang:
                type: string
                example: EN
              title:
                type: string
                example: Certificate of Birth
        descriptionLang:
          type: array
          items:
            type: object
            properties:
              lang:
                type: string
                example: EN
              description:
                type: string
                example: An official certificate of birth of a person - with first name, surname, sex, date and place of birth, which is obtained from the birth register of the place of birth.
        jurisdiction:
          $ref: '#/components/schemas/Jurisdiction'
    DistributedAs:
      type: object
      properties:
        Format:
          type: string
          example: Code
        ConformsTo:
          type: string
          example: URI
        Transformation:
          type: string
          example: URI
    EvidenceProviderJurisdictionDetermination:
      type: object
      properties:
        JurisdictionContextId:
          type: string
        JurisdictionContext:
          type: string
          example: Text
        JurisdictionContextTextLang:
          type: string
          example: Code
        JurisdictionLevel:
          type: string
          example: Code
    EvidenceProviderClassification:
      type: object
      properties:
        id:
          type: string
        Type:
          type: string
          example: Text
        ValueExpression:
          type: string
          example: Text
        DescriptionLang:
          type: string
          example: Code
    PublisherDataServiceEvidenceProvider:
      type: object
      required:
        - identifier
        - identifierSchemeID
        - name
        - nameLang
        - descriptionLang
        - address
      description: >-
          A Node defining the registry object as an Evidence Provider (Publisher) Entity
      properties:
        identifier:
          type: string
          example: RO4433775
        identifierSchemeID:
          type: string
          example: RO VAT Code
        nameLang:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                description: Name of the provider
                example: Bucharest University of Economic Studies
              lang:
                type: string
                example: EN
        descriptionLang:
          type: array
          items:
            type: object
            properties:
              description:
                type: string
                description: Name of the provider
                example: Bucharest University of Economic Studies
              lang:
                type: string
                example: EN
        address:
          $ref: '#/components/schemas/Address'
    Address:
      type: object
      properties:
        City:
          type: string
          description: City name of the agent's address
          example: Amsterdam
        PostalCode:
          type: string
          description: Postal code of the agent's address
          example: 1012
        Street:
          type: string
          description: Full address of the agent
          example: Binnengasthuisstraat
        StreetNumber:
          type: string
          description: Designator of the locator
          example: 9
        AdtionalAdressDetails:
          type: string
          example: building, apartment number. floor, etc
        jurisdiction:
          $ref: '#/components/schemas/Jurisdiction'

    Jurisdiction:
      type: object
      required:
        - adminUnitLevel1
      properties:
        adminUnitLevel1:
          type: string
          example: Code - ex. DE
        adminUnitLevel2:
          type: string
          example: Code
        adminUnitLevel3:
          type: string
          example: Code
    ClassificationConcept:
      type: object
      required:
        - identifier
      properties:
        identifier:
          type: string
        type:
          type: string
          example: Text
        valueExpression:
          type: string
          example: Text
        description:
          type: array
          items:
            type: string
            example: Text
        descriptionLang:
          type: string
          example: Code
        supportedValue:
          $ref: '#/components/schemas/SupportedValue'
    SupportedValue:
      type: object
      properties:
        stringValue:
          type: array
          items:
            type: string
            example: Text
        dateValue:
          type: array
          items:
            type: string
            format: date
        booleanValue:
          type: array
          items:
            type: boolean
            
    Procedure:
        type: object
        description: >-
          This Registry Object ReferenceFramework provides the information of a Procedure. It MUST NOT contain any relations to other Reference Frameworks (Procedures) as this are provided dynamically by the use of associations. The classification node used MUST be ReferenceFramework under the EB Classification Scheme urn:fdc:oots:classification:eb.
        properties:
          Identifier:
            type: string
            example: "118fd444-6443-42be-a084-c9fbfd1f674d"
          Title:
            type: array
            items:
              type: object
              properties:
                lang:
                  type: string
                text:
                  type: string
            example:
              - lang: "EN"
                text: "Procedure #1 - Requesting proof of registration of birth"
              - lang: "DE"
                text: "Verfahren #1 - Beantragung des Nachweises über die Eintragung in das Geburtenregister"
          Description:
            type: array
            items:
              type: object
              properties:
                lang:
                  type: string
                text:
                  type: string
            example:
              - lang: "EN"
                text: "Procedure #1 'Requesting proof of registration of birth' belongs to the life event 'Birth' of Annex II of the Regulation (EU) 2018/1724 of the European Parliament and of the Council of 2 October 2018 establishing a single digital gateway to provide access to information, to procedures and to assistance and problem-solving services and amending Regulation (EU) No 1024/2012."
              - lang: "DE"
                text: "Das Verfahren #1 'Beantragung des Nachweises über die Eintragung in das Geburtenregister' gehört zum Lebensereignis 'Geburt' des Anhangs II der Verordnung (EU) 2018/1724 des Europäischen Parlaments und des Rates vom 2. Oktober 2018 über die Einrichtung eines einheitlichen digitalen Zugangstors zu Informationen, Verfahren, Hilfsund Problemlösungsdiensten und zur Änderung der Verordnung (EU) Nr. 1024/2012."
          RelatedTo:
            type: string
            description: The Identifier of the SDGR Procedure which this procedure relates to encoded according to Procedures-CodeList.gc. In this case R1 relates to "Requesting a birth certificate"
            example: "R1"
          Jurisdiction:
              $ref: '#/components/schemas/Jurisdiction'
          RequirementsMapping:
              type: array
              items:
                type: object
                properties:
                  requirementId: 
                    $ref: '#/components/schemas/Requirement/properties/id'
                  evidenceTypeClassificationId:
                    $ref: '#/components/schemas/EvidenceTypeClassification/properties/id'
                          

    EvidenceTypeList:
      type: object
      description: >-
        This Registry Object provides the information of the Evidence Type List. It works as an intermediate class linking multiple evidence types as an atomic proof to requirements and thus it MUST NOT contain any evidence types in its structure. The classification node used MUST be EvidenceTypeList under the EB Classification Scheme urn:fdc:oots:classification:eb.
      properties:
        Identifier:
          type: string
          example: 970918e4-1b27-41f0-be20-0a7c5fe4059f
        NameLang: 
          type: array
          items:
              type: object
              properties:
                lang:
                  type: string
                text:
                  type: string
              example:
                - lang: "EN"
                  text: "List of Birth Certificates"
                - lang: "DE"
                  text: "Liste der Geburtsurkunden"
        
    ContainsEvidence:
      type: object
      description: >-
        This Association provides the link between an Evidence Type List and an Evidence Type. The type attribute MUST be urn:oasis:names:tc:ebxml-regrep:AssociationType:ContainsEvidence, with the source object pointing to an EvidenceTypeList RegistryObject through the use of its rim:RegistryObject id and the targetObject pointing to rim:RegistryObject id of an EvidenceType object.  Evidence Types of an Evidence Type List are combined via the logic operator ‘AND’. An Evidence Type List is satisfied, if and only if, for all included Evidence Types in this List, corresponding conformant Evidence(s) are provided.
      properties:
        id:
          type: string
          description: A unique id for this association
          example: 826a2206-5dd0-45ff-abbc-23ba8f38477f
        evidenceTypeListId:
          type: string
          description: >-
            The sourceObject is the 'rim:RegistryObject' id of the EvidenceTypeList "970918e4-1b27-41f0-be20-0a7c5fe4059f"
          example: 970918e4-1b27-41f0-be20-0a7c5fe4059f
        evidenceTypeId:
          type: string
          description: >-
            The targetObject is the 'rim:RegistryObject' id of the EvidenceType "Certificate of Birth"
          example: a1be6e74-e9ba-4d44-b04c-0376f367b8fd
      
    FulfillsRequirement:
      type: object
      description: >-
        This Association provides the link between an Evidence Type List and a Requirement. The type attribute MUST be urn:oasis:names:tc:ebxml-regrep:AssociationType:FulfillsRequirement, with the source object pointing to an EvidenceTypeList RegistryObject through the use of its rim:RegistryObject id and the targetObject pointing to the rim:RegistryObject id of an Requirement object.  Evidence Type Lists that fulfill the same Requirement are combined via the logic operator ‘OR’.
      properties:
        id:
          type: string
          description: A unique id for this association
          example: 3da4288b-e2ca-4d40-bde2-d3fc2dd04bab
        evidenceTypeListId:
          type: string
          description: >-
            The sourceObject is the 'rim:RegistryObject' id of the EvidenceTypeList "970918e4-1b27-41f0-be20-0a7c5fe4059f"
          example: 91197b3c-890b-475f-a07e-709742e59f23
        requirementId:
          type: string
          description: >-
            The targetObject is the 'rim:RegistryObject' id of the Requirement "Proof of Birth"
          example: 315cfd75-6605-49c4-b0fe-799833b41099
          
    DerivesFromReferenceFramework:
      type: object
      description: >-
        This Association provides the link between a Requirement and a ReferenceFramework (Procedure). The type attribute MUST be urn:oasis:names:tc:ebxml-regrep:AssociationType:DerivesFromReferenceFramework, with the source object pointing to a Requirement RegistryObject through the use of its rim:RegistryObject id and the targetObject pointing to the rim:RegistryObject id of a ReferenceFramework object.
        
          Example: Associate the Requirement "Proof of Birth" with ReferenceFramework "Procedure #1 - Requesting proof of registration of birth
      properties:
        id:
          type: string
          description: A unique id for this association
          example: d650d08b-4ca3-4d04-a5d2-255d83b84ce1
        requirementId:
          type: string
          description: >-
            The targetObject is the 'rim:RegistryObject' id of the Requirement "Proof of Birth"
          example: 315cfd75-6605-49c4-b0fe-799833b41099   
        procedureId:
          type: string
          description: >-
            The targetObject is the 'rim:RegistryObject' id of the ReferenceFramework "Procedure #1 - Requesting proof of registration of birth"
          example: b0c90eb4-6b66-4dd8-8c79-6d964ac3b9a1
    EvidenceTypeProvider:
      type: object
      properties:
        requirementId: 
          $ref: '#/components/schemas/Requirement/properties/id'
        evidenceTypeClassificationId:
          $ref: '#/components/schemas/EvidenceTypeClassification/properties/id'
    PreviewResponse:
      type: object
      properties:
        Procedure:
          $ref: '#/components/schemas/Procedure'
        Requirement:
          $ref: '#/components/schemas/Requirement'
        EvidenceResponse:
          $ref: '#/components/schemas/EvidenceResponse'

      
              

      